ziri-bros/high-geupsik-backend

- .github/workflows/ci.yml
- src/main/resources/application-aws.yml
- src/main/resources/application-db.yml
- src/main/resources/application-file.yml
- src/main/resources/application-mail.yml
- src/main/resources/application.yml
- src/test/resources/application-aws.yml
- src/test/resources/application-file.yml
- src/test/resources/application-mail.yml
- src/test/resources/application-oauth.yml
- src/test/resources/application-test-db.yml
- src/test/resources/application.yml
❓ [변경점]
yml 파일의 가독성 및 유지보수성 향상을 위해 여러개로 나눔
gradlew test시 testdb를 h2로 변경
secrets 환경변수 관리
@baeseohyeon @ziri-bros/backend
> ci: ci 및 yml 설정 변경

- src/main/java/com/highgeupsik/backend/entity/School.java
1️⃣ 정규화/비즈니스 지원을 위한 school table 분리
❓ 아직 schoolInfo 자체를 지우지는 않았음 -> 이후 바꿀 예정
> refactor: school table 분리

- src/main/java/com/highgeupsik/backend/api/BoardDetailApiController.java
- src/main/java/com/highgeupsik/backend/api/ImageApiController.java
- src/main/java/com/highgeupsik/backend/api/UserApiController.java
- src/main/java/com/highgeupsik/backend/dto/BoardDetailReqDTO.java
- src/main/java/com/highgeupsik/backend/dto/BoardDetailResDTO.java
- src/main/java/com/highgeupsik/backend/dto/UploadFileDTO.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/repository/BoardRepositoryImpl.java
- src/main/java/com/highgeupsik/backend/service/BoardDetailService.java
- src/main/java/com/highgeupsik/backend/service/S3Service.java
- src/main/java/com/highgeupsik/backend/service/UploadFileService.java
- src/main/java/com/highgeupsik/backend/service/UserCardService.java
이미지 업로드 API 추가
게시글 저장 로직 변경 
Board의 thumbnail컬럼 UploadFile과 일대일 관계에서 String컬럼으로 변경
> feat: 이미지 업로드 API 추가

- src/main/java/com/highgeupsik/backend/api/BoardDetailApiController.java
- src/main/java/com/highgeupsik/backend/service/BoardDetailService.java
board service 의 Post가 들어가있는 함수명을 board로 변경 했습니다
> refactor: board service 함수 이름 변경

- src/main/java/com/highgeupsik/backend/api/BoardApiController.java
- src/main/java/com/highgeupsik/backend/api/CommentApiController.java
- src/main/java/com/highgeupsik/backend/api/ImageApiController.java
- src/main/java/com/highgeupsik/backend/api/UserApiController.java
- src/main/java/com/highgeupsik/backend/api/UserCardApiController.java
- src/main/java/com/highgeupsik/backend/config/Swagger2Config.java
- src/main/java/com/highgeupsik/backend/config/WebSecurityConfig.java
Swagger2Config 추가
Webignoring 추가
ApiOperation 추가
했습니다
> Feat/swagger UI

- src/main/java/com/highgeupsik/backend/utils/CookieUtils.java
> feat: CookieUtils 추가

- src/main/java/com/highgeupsik/backend/repository/UserCardRepository.java
- src/main/java/com/highgeupsik/backend/service/UserCardQueryService.java
> feat: 유저아이디로 학생증 조회 추가

- src/main/java/com/highgeupsik/backend/handler/OAuth2AuthenticationSuccessHandler.java
바디로만 담아주는것에서
유저정보와 토큰을 url에 queryParameter로 담아서 프런트 주소로 redirect해주는 로직으로 변경
> refactor: 유저정보와 토큰을queryParameter로 담아서 redirect해주는 로직으로 변경

- src/main/java/com/highgeupsik/backend/dto/SchoolDTO.java
- src/main/java/com/highgeupsik/backend/entity/School.java
> feat: SchoolDTO 추가

- src/main/java/com/highgeupsik/backend/api/UserApiController.java
- src/main/java/com/highgeupsik/backend/dto/UserCardReqDTO.java
- src/main/java/com/highgeupsik/backend/dto/UserCardResDTO.java
- src/main/java/com/highgeupsik/backend/entity/UserCard.java
- src/main/java/com/highgeupsik/backend/service/UserCardService.java
usercard entity의 uploadfile을 String 타입으로 변경, School entity를 추가했습니다
> refactor: School추가 uploadeFile을 String으로 변경

- src/main/java/com/highgeupsik/backend/dto/SchoolDTO.java
- src/main/java/com/highgeupsik/backend/entity/School.java
> refactor: regionCode 컬럼 추가

- src/main/java/com/highgeupsik/backend/config/WebSecurityConfig.java
1. cors 추가
2. /images 경로 permitAll 추가
했습니다
> refactor: cors 추가, /images permitAll 추가

- src/main/java/com/highgeupsik/backend/handler/OAuth2AuthenticationSuccessHandler.java
> chore: 리다이렉트 주소 클라이언트의 로컬호스트로 변경

- src/main/java/com/highgeupsik/backend/config/Swagger2Config.java
> refactor: swagger 전역 jwt token 추가

- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/highgeupsik/backend/api/UserApiController.java
- src/main/java/com/highgeupsik/backend/dto/BoardResDTO.java
- src/main/java/com/highgeupsik/backend/repository/BoardRepositoryImpl.java
게시글 조회할때 작성자 아이디와 작성날짜도 추가했습니다
> chore: board res dto

- src/main/java/com/highgeupsik/backend/api/BoardApiController.java
- src/main/java/com/highgeupsik/backend/api/CommentApiController.java
- src/main/java/com/highgeupsik/backend/service/LikeService.java
> feat: 좋아요 조회 API 추가

- src/main/java/com/highgeupsik/backend/api/BoardLikeController.java
- src/main/java/com/highgeupsik/backend/api/CommentLikeController.java
- src/main/java/com/highgeupsik/backend/dto/LikeDTO.java
- src/main/java/com/highgeupsik/backend/service/LikeService.java
- src/main/java/com/highgeupsik/backend/utils/ErrorMessage.java
like dto 추가 
like 조회 로직 변경
comment api 댓글 좋아요 조회 삭제
> refactor: like service

- src/main/java/com/highgeupsik/backend/api/CommentController.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
> refactor(Comment): 삭제 로직 수정

- src/main/java/com/highgeupsik/backend/api/UserApiController.java
- src/main/java/com/highgeupsik/backend/dto/BoardResDTO.java
- src/main/java/com/highgeupsik/backend/dto/StudentCardDTO.java
- src/main/java/com/highgeupsik/backend/dto/UserResDTO.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/StudentCard.java
- src/main/java/com/highgeupsik/backend/repository/BoardRepositoryImpl.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
- src/main/java/com/highgeupsik/backend/utils/ErrorMessage.java
- src/main/java/com/highgeupsik/backend/utils/checkUtils.java
student card 엔티티에 학년 반 컬럼 추가
체크유틸 삭제
> refactor: student card entity

- src/main/java/com/highgeupsik/backend/dto/CommentResDTO.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/repository/BoardRepository.java
- src/main/java/com/highgeupsik/backend/repository/CommentRepository.java
- src/main/java/com/highgeupsik/backend/service/CommentQueryService.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
> Feat: comment reploy count

- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
- 댓글이 삭제되지 않고 disable만 되던 문제 해결
- Board에서 Comment를 OrphanRemoval 하도록 수정
> fix(Comment): 댓글 삭제 로직의 오류 수정

- src/main/java/com/highgeupsik/backend/api/AdminApiController.java
- src/main/java/com/highgeupsik/backend/api/UserProfileController.java
- src/main/java/com/highgeupsik/backend/repository/UserRepository.java
- src/main/java/com/highgeupsik/backend/service/UserConfirmService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
> refactor: user service

- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/dto/BoardResDTO.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
Board 엔티티에 setThumbnail추가
BoardService에 makeBoard추가
> refactor(BoardService): 게시글 저장 로직 변경

- src/main/java/com/highgeupsik/backend/api/BoardLikeController.java
- src/main/java/com/highgeupsik/backend/entity/Like.java
- src/main/java/com/highgeupsik/backend/service/LikeService.java
Like 엔티티에 of 메소드 추가
좋아요 저장 로직 변경
> refactor(LikeService): 좋아요 저장 로직 변경

- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/repository/UploadFileRepository.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
Board Entity의 uploadFileList 에 orphanRemoval 추가
Board Service에 이미지 추가 함수 작성
> refactor(BoardSevice): 이미지 추가 함수 분할 

- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
Board : checkWriter 추가
BoardController : (GET)editBoard 삭제
BoardService : 업데이트, 삭제에 checkWriter 추가
> refactor(BoardService): board service 

- src/main/java/com/highgeupsik/backend/api/CommentController.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/repository/CommentRepository.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
Board : isWriter(User)삭제, addComment 변경
CommentRepository,CommentController : deletComment (boardId)인자 삭제
CommentService : Comment 저장 로직 변경
> refactor(CommentService): comment 저장 로직 변경

- src/main/java/com/highgeupsik/backend/jwt/JwtAuthenticationFilter.java
- src/main/java/com/highgeupsik/backend/jwt/JwtTokenProvider.java
- src/main/java/com/highgeupsik/backend/service/UserQueryService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
loadByUsername삭제, valideToken 변경
> refactor(UserService,TokenProvider): loadByUsername삭제, valideToken 변경 

- src/main/java/com/highgeupsik/backend/oauth2/CustomOAuth2UserService.java
- src/main/java/com/highgeupsik/backend/oauth2/SocialUser.java
> refactor(SocialUser):  SocialUser 변경 

- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/service/BoardQueryService.java
목록 조회할때 프런트에서 리덕스를 이용하여 region을 함께 서버에 넘기는 로직으로 변경
> refactor(BoardQueryService): 목록조회 로직 변경

- src/main/java/com/highgeupsik/backend/api/AdminApiController.java
- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/api/BoardLikeController.java
- src/main/java/com/highgeupsik/backend/api/CommentLikeController.java
- src/main/java/com/highgeupsik/backend/api/ScheduleController.java
- src/main/java/com/highgeupsik/backend/service/CommentQueryService.java
> chore(CommentService): createdDate 내림차순 조회로 변경

- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/api/BoardLikeController.java
- src/main/java/com/highgeupsik/backend/api/UserBoardController.java
- src/main/java/com/highgeupsik/backend/dto/BoardResDTO.java
- src/main/java/com/highgeupsik/backend/service/BoardQueryService.java
- src/main/java/com/highgeupsik/backend/service/LikeService.java
BoardResDTO에 isUserLike를 추가했습니다.
BoardQueryService의 getUserLike 함수를 더 이쁘게 해줄수있나요?
> refactor(BoardQueryService): isUserLike 기능 추가

- src/main/java/com/highgeupsik/backend/api/AdminApiController.java
- src/main/java/com/highgeupsik/backend/service/UserConfirmService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
유저승인삭제처리 로직을 컨트롤러에서 서비스로 변경했습니다.
> refactor(userService): 유저승인거부함수 추가

- src/main/java/com/highgeupsik/backend/api/ScheduleController.java
- src/main/java/com/highgeupsik/backend/dto/SubjectScheduleDTO.java
- src/main/java/com/highgeupsik/backend/service/SubjectScheduleService.java
> refactor: subject schedule

- build.gradle
- src/main/java/com/highgeupsik/backend/api/AuthController.java
- src/main/java/com/highgeupsik/backend/api/ErrorApiController.java
- src/main/java/com/highgeupsik/backend/config/WebSecurityConfig.java
- src/main/java/com/highgeupsik/backend/entity/User.java
- src/main/java/com/highgeupsik/backend/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/highgeupsik/backend/jwt/JwtAuthenticationFilter.java
- src/main/java/com/highgeupsik/backend/jwt/JwtTokenProvider.java
- src/main/java/com/highgeupsik/backend/oauth2/CustomOAuth2UserService.java
- src/main/java/com/highgeupsik/backend/repository/UserRepository.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
- src/main/java/com/highgeupsik/backend/service/UserTokenService.java
refreshToken 사용할수 있도록 로그인 로직과 토큰을 요청하는 로직을 변경했습니다.
> refactor(JwtTokenProvider): refreshToken 사용

- src/main/java/com/highgeupsik/backend/api/UserProfileController.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
> chore(UserProfileController): userModify 리턴 변경

- src/main/java/com/highgeupsik/backend/api/MessageApiController.java
- src/main/java/com/highgeupsik/backend/dto/RoomResDTO.java
- src/main/java/com/highgeupsik/backend/entity/Message.java
- src/main/java/com/highgeupsik/backend/entity/Room.java
- src/main/java/com/highgeupsik/backend/repository/MessageRepository.java
- src/main/java/com/highgeupsik/backend/repository/RoomRepository.java
- src/main/java/com/highgeupsik/backend/service/MessageQueryService.java
- src/main/java/com/highgeupsik/backend/service/MessageService.java
- src/main/java/com/highgeupsik/backend/service/RoomQueryService.java
- src/main/java/com/highgeupsik/backend/service/RoomService.java
> chore: 코드 삭제

- src/main/java/com/highgeupsik/backend/entity/Message.java
- src/main/java/com/highgeupsik/backend/entity/Room.java
- src/main/java/com/highgeupsik/backend/service/RoomMessageService.java
> chore(Room): user fk 컬럼 이름 수정

- build.gradle
- src/main/java/com/highgeupsik/backend/api/ImageApiController.java
- src/main/java/com/highgeupsik/backend/service/S3Service.java
- src/main/resources/application-aws.yml
- src/main/resources/application-oauth.yml
S3 Sdk 버전을 2.2.1 -> 2.2.6 으로 업그레이드
그에따라 yml 설정 수정 및 코드 리팩토링
> refactor: s3 이미지 업로드 의존성 버전업그레이드 및 그에따른 리팩토링

- src/main/java/com/highgeupsik/backend/api/SchoolController.java
- src/main/java/com/highgeupsik/backend/api/UserProfileController.java
- src/main/java/com/highgeupsik/backend/dto/SchoolReqDTO.java
- src/main/java/com/highgeupsik/backend/dto/SchoolResDTO.java
- src/main/java/com/highgeupsik/backend/dto/UserResDTO.java
- src/main/java/com/highgeupsik/backend/entity/Region.java
- src/main/java/com/highgeupsik/backend/repository/SchoolRepository.java
- src/main/java/com/highgeupsik/backend/service/SchoolService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
지역과 학교이름을 이용한 학교조회 추가
클라이언트에서 학교가 있는지 확인하는 API 추가
> refactor(SchoolService): 지역과 학교이름을 이용한 학교 조회 추가 

- src/main/java/com/highgeupsik/backend/entity/School.java
- src/main/java/com/highgeupsik/backend/utils/InitDB.java
- src/main/java/com/highgeupsik/backend/utils/ParsingUtils.java
- src/main/resources/application-db.yml
jpa batch insert 를 사용하기위해 학교 테이블 키생성 전략을 테이블 전략으로 수정
> refactor: 학교 데이터를 넣을때 jpa batch insert 를 사용하도록 수정 

- build.gradle
- src/main/java/com/highgeupsik/backend/utils/ApiError.java
- src/main/java/com/highgeupsik/backend/utils/ParsingUtils.java
- src/main/resources/application-log.yml
- src/main/resources/application.yml
- src/main/resources/logback-slack.xml
> feat: 슬랙 에러로그 기능 추가 

- src/main/java/com/highgeupsik/backend/entity/Subject.java
- src/main/java/com/highgeupsik/backend/entity/SubjectSchedule.java
- src/main/java/com/highgeupsik/backend/service/SubjectScheduleService.java
시간표를 저장하기전 원래있던 시간표의 과목들을 삭제하도록 orphanRemoval 을 추가
> refactor: 시간표 로직 변경

- src/main/java/com/highgeupsik/backend/api/AdminApiController.java
- src/main/java/com/highgeupsik/backend/api/ErrorApiController.java
- src/main/java/com/highgeupsik/backend/exception/MailException.java
- src/main/java/com/highgeupsik/backend/service/MailService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
throws -> try catch로 변경하여 메일서비스 안에서 에러처리를 하도록 수정
> refactor(MailService): 메일 에러처리를 메일서비스에서 하도록 수정

- build.gradle
- src/main/java/com/highgeupsik/backend/aop/aspect/RetryAspect.java
- src/main/java/com/highgeupsik/backend/aop/aspect/TraceAspect.java
- src/main/java/com/highgeupsik/backend/aop/pointcuts/PointCuts.java
- src/main/java/com/highgeupsik/backend/config/AopConfig.java
- src/main/java/com/highgeupsik/backend/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/highgeupsik/backend/jwt/JwtAuthenticationFilter.java
- src/main/java/com/highgeupsik/backend/jwt/JwtTokenProvider.java
> feat: 로그추적, 재시도 로직 추가

- src/main/java/com/highgeupsik/backend/repository/BoardRepositoryImpl.java
> refactor: or 절을위해 검색필터링 builder로 수정

- build.gradle
- src/main/java/com/highgeupsik/backend/api/ApiExceptionController.java
- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/api/SchoolController.java
- src/main/java/com/highgeupsik/backend/dto/BoardSearchCondition.java
- src/main/java/com/highgeupsik/backend/dto/SchoolSearchCondition.java
- src/main/java/com/highgeupsik/backend/utils/ErrorMessage.java
> feat: @Valid를 이용하여 게시글, 학교 리스트 조회시 검증 추가 

- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/repository/BoardRepositoryImpl.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
> refactor: 게시글 삭제 로직 수정

- src/main/java/com/highgeupsik/backend/api/ApiExceptionController.java
- src/main/java/com/highgeupsik/backend/api/RoomMessageController.java
- src/main/java/com/highgeupsik/backend/dto/MessageReqDTO.java
- src/main/java/com/highgeupsik/backend/dto/RoomDTO.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/entity/Message.java
- src/main/java/com/highgeupsik/backend/entity/Room.java
- src/main/java/com/highgeupsik/backend/exception/NotWriterException.java
- src/main/java/com/highgeupsik/backend/exception/UserException.java
- src/main/java/com/highgeupsik/backend/repository/MessageRepository.java
- src/main/java/com/highgeupsik/backend/repository/RoomRepository.java
- src/main/java/com/highgeupsik/backend/service/MessageQueryService.java
- src/main/java/com/highgeupsik/backend/service/RoomMessageService.java
- src/main/java/com/highgeupsik/backend/service/RoomQueryService.java
- src/main/java/com/highgeupsik/backend/utils/ErrorMessage.java
> refactor: message logic

- src/main/java/com/highgeupsik/backend/api/BoardCommentController.java
- src/main/java/com/highgeupsik/backend/repository/CommentRepositoryImpl.java
- src/main/java/com/highgeupsik/backend/service/BoardCommentService.java
> refactor(CommentRepositoryImpl): 페이징 조건 추가

- src/main/java/com/highgeupsik/backend/api/AdminApiController.java
- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/api/BoardLikeController.java
- src/main/java/com/highgeupsik/backend/api/CommentController.java
- src/main/java/com/highgeupsik/backend/api/CommentLikeController.java
- src/main/java/com/highgeupsik/backend/api/ImageApiController.java
- src/main/java/com/highgeupsik/backend/api/RoomMessageController.java
- src/main/java/com/highgeupsik/backend/api/ScheduleController.java
- src/main/java/com/highgeupsik/backend/api/UserProfileController.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
- src/main/java/com/highgeupsik/backend/service/LikeService.java
- src/main/java/com/highgeupsik/backend/service/RoomMessageService.java
- src/main/java/com/highgeupsik/backend/service/UserService.java
> style: 컨트롤러 메소드명 변경

- src/main/java/com/highgeupsik/backend/api/AlarmController.java
- src/main/java/com/highgeupsik/backend/api/ApiExceptionController.java
- src/main/java/com/highgeupsik/backend/api/NotificationController.java
- src/main/java/com/highgeupsik/backend/config/AsyncConfig.java
- src/main/java/com/highgeupsik/backend/dto/NotificationDTO.java
- src/main/java/com/highgeupsik/backend/entity/Notification.java
- src/main/java/com/highgeupsik/backend/entity/NotificationType.java
- src/main/java/com/highgeupsik/backend/events/AlarmEvent.java
- src/main/java/com/highgeupsik/backend/exception/SseException.java
- src/main/java/com/highgeupsik/backend/handler/EventHandler.java
- src/main/java/com/highgeupsik/backend/repository/EmitterRepository.java
- src/main/java/com/highgeupsik/backend/repository/NotificationRepository.java
- src/main/java/com/highgeupsik/backend/service/AlarmService.java
- src/main/java/com/highgeupsik/backend/service/AlarmServiceImpl.java
- src/main/java/com/highgeupsik/backend/service/NotificationQueryService.java
- src/main/java/com/highgeupsik/backend/service/NotificationService.java
- src/main/java/com/highgeupsik/backend/utils/ErrorMessage.java
- src/main/java/com/highgeupsik/backend/utils/NotificationMessage.java
> feat: 댓글 대댓글 메세지 알림 서비스 

- src/main/java/com/highgeupsik/backend/api/ApiExceptionController.java
- src/main/java/com/highgeupsik/backend/api/BoardController.java
- src/main/java/com/highgeupsik/backend/api/BoardLikeController.java
- src/main/java/com/highgeupsik/backend/api/CommentController.java
- src/main/java/com/highgeupsik/backend/api/CommentLikeController.java
- src/main/java/com/highgeupsik/backend/api/UserProfileController.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
- src/main/java/com/highgeupsik/backend/service/NotificationService.java
- src/main/java/com/highgeupsik/backend/service/RoomMessageService.java
> feat: connect alarm service

- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
댓글삭제시 바로 삭제하지 않도록 수정, 대댓글 리스트에 케스케이드 추가
> refactor: 댓글삭제

- src/main/java/com/highgeupsik/backend/dto/NotificationDTO.java
- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/entity/Notification.java
- src/main/java/com/highgeupsik/backend/entity/Room.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
- src/main/java/com/highgeupsik/backend/service/NotificationQueryService.java
- src/main/java/com/highgeupsik/backend/service/NotificationService.java
> refactor: 알림 연관관계 추가

- src/main/java/com/highgeupsik/backend/api/UserBoardController.java
- src/main/java/com/highgeupsik/backend/repository/BoardRepository.java
- src/main/java/com/highgeupsik/backend/service/BoardQueryService.java
> refactor: 내가 댓글단 게시글 목록 조회 추가

- src/main/java/com/highgeupsik/backend/api/NotificationController.java
- src/main/java/com/highgeupsik/backend/dto/NotificationDTO.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
- src/main/java/com/highgeupsik/backend/service/NotificationQueryService.java
- src/main/java/com/highgeupsik/backend/service/NotificationService.java
> refactor: 대댓글 알림 추가

- src/main/java/com/highgeupsik/backend/service/CommentService.java
- src/test/resources/application.yml
Notification 저장할때 잘못된 유저와 연관관계가 설정되는 오류 수정
> refactor: Notification 받는 유저 저장 수정

- src/main/java/com/highgeupsik/backend/api/RoomMessageController.java
- src/main/java/com/highgeupsik/backend/dto/BoardResDTO.java
- src/main/java/com/highgeupsik/backend/dto/MessageReqDTO.java
- src/main/java/com/highgeupsik/backend/dto/MessageResDTO.java
- src/main/java/com/highgeupsik/backend/dto/RoomDTO.java
- src/main/java/com/highgeupsik/backend/entity/Message.java
- src/main/java/com/highgeupsik/backend/entity/Room.java
- src/main/java/com/highgeupsik/backend/repository/RoomRepository.java
- src/main/java/com/highgeupsik/backend/service/NotificationService.java
- src/main/java/com/highgeupsik/backend/service/RoomMessageService.java
- src/main/java/com/highgeupsik/backend/service/RoomQueryService.java
> refactor(Room): 필드명 수정 

- src/main/java/com/highgeupsik/backend/entity/School.java
- src/main/java/com/highgeupsik/backend/utils/ParsingUtils.java
> feat: 학교 도메인 홈페이지 컬럼 추가

- src/main/java/com/highgeupsik/backend/entity/Message.java
- src/main/java/com/highgeupsik/backend/entity/Room.java
- src/main/java/com/highgeupsik/backend/repository/RoomRepository.java
- src/main/java/com/highgeupsik/backend/service/RoomMessageService.java
- src/main/java/com/highgeupsik/backend/service/RoomQueryService.java
- src/test/java/com/highgeupsik/backend/entity/MessageTest.java
- src/test/java/com/highgeupsik/backend/entity/RoomTest.java
- src/test/java/com/highgeupsik/backend/repository/MessageRepositoryTest.java
- src/test/java/com/highgeupsik/backend/repository/RoomMessageRepository.java
- src/test/java/com/highgeupsik/backend/repository/RoomRepositoryTest.java
- src/test/java/com/highgeupsik/backend/service/RoomMessageServiceTest.java
> test: Room/Message 테스트 추가

- src/main/java/com/highgeupsik/backend/entity/Board.java
- src/main/java/com/highgeupsik/backend/entity/Comment.java
- src/main/java/com/highgeupsik/backend/entity/User.java
- src/main/java/com/highgeupsik/backend/service/BoardService.java
- src/main/java/com/highgeupsik/backend/service/CommentService.java
> refactor: comment service

- src/main/java/com/highgeupsik/backend/api/timetable/SubjectDto.java
- src/main/java/com/highgeupsik/backend/api/timetable/TimetableController.java
- src/main/java/com/highgeupsik/backend/api/timetable/TimetableDto.java
- src/main/java/com/highgeupsik/backend/api/timetable/neis/Row.java
- src/main/java/com/highgeupsik/backend/api/timetable/neis/Schedule.java
- src/main/java/com/highgeupsik/backend/api/timetable/neis/Timetable.java
- src/main/java/com/highgeupsik/backend/api/timetable/neis/TimetableRequestCondition.java
- src/main/java/com/highgeupsik/backend/service/timetable/TimetableService.java
- src/main/java/com/highgeupsik/backend/utils/MyDateUtils.java
- src/main/java/com/highgeupsik/backend/utils/OpenApiRequestUtils.java
- src/main/java/com/highgeupsik/backend/utils/UrlUtils.java
> feat: 공공 시간표 조회 추가

- src/main/java/com/highgeupsik/backend/api/admin/AdminApiController.java
- src/main/java/com/highgeupsik/backend/api/school/SchoolResDTO.java
- src/main/java/com/highgeupsik/backend/api/subjectschedule/neis/TimetableRequestCondition.java
- src/main/java/com/highgeupsik/backend/api/user/UserResDTO.java
- src/main/java/com/highgeupsik/backend/entity/board/Board.java
- src/main/java/com/highgeupsik/backend/entity/board/Comment.java
- src/main/java/com/highgeupsik/backend/entity/board/Like.java
- src/main/java/com/highgeupsik/backend/entity/message/Message.java
- src/main/java/com/highgeupsik/backend/entity/message/Room.java
- src/main/java/com/highgeupsik/backend/entity/notification/Notification.java
- src/main/java/com/highgeupsik/backend/entity/school/School.java
- src/main/java/com/highgeupsik/backend/entity/school/StudentCard.java
- src/main/java/com/highgeupsik/backend/entity/user/User.java
- src/main/java/com/highgeupsik/backend/entity/user/UserConfirm.java
- src/main/java/com/highgeupsik/backend/repository/user/UserRepository.java
- src/main/java/com/highgeupsik/backend/service/SubjectScheduleService.java
- src/main/java/com/highgeupsik/backend/service/board/BoardService.java
- src/main/java/com/highgeupsik/backend/service/user/UserAdminService.java
- src/main/java/com/highgeupsik/backend/service/user/UserService.java
> refactor: 학생증 테이블 수정

- .github/workflows/ci.yml
- build.gradle
- src/main/java/com/highgeupsik/backend/config/Swagger2Config.java
- src/main/java/com/highgeupsik/backend/config/WebSecurityConfig.java
- src/main/java/com/highgeupsik/backend/repository/board/BoardRepositoryImpl.java
- src/main/java/com/highgeupsik/backend/repository/comment/CommentRepositoryImpl.java
- src/main/java/com/highgeupsik/backend/repository/school/SchoolRepositoryImpl.java
- src/main/resources/application-mvc.yml
- src/main/resources/application.yml
> build: 스프링 부트 버전 2.7.5로 업그레이드
